import { Article, Race, Category } from "@/types";

// AUTO-ARTICLES:START (généré par scripts/publish.mjs — ne pas éditer à la main)
const generatedArticles: Article[] = [];
// AUTO-ARTICLES:END

export const categories: Category[] = [
  { slug: "actualites", label: "Actualités", description: "Les dernières nouvelles du monde du trail running" },
  { slug: "debuter", label: "Débuter", description: "Tous les conseils pour se lancer dans le trail" },
  { slug: "courses-recits", label: "Courses & Récits", description: "Récits de course et comptes rendus" },
  { slug: "nutrition", label: "Nutrition", description: "Alimentation et ravitaillement pour le trail" },
  { slug: "entrainement", label: "Entraînement & Performances", description: "Plans d'entraînement et conseils de performance" },
  { slug: "blessures", label: "Blessures & Préventions", description: "Prévention et récupération des blessures" },
];

export const articles: Article[] = [
  ...generatedArticles,
  {
    slug: "diagonale-des-fous-2024",
    title: "DIAGONALE DES FOUS : LE MYTHE RÉINVENTÉ.",
    excerpt: "Traverser l'île de la Réunion n'est plus une course, c'est un pèlerinage brutal vers la limite de soi. Décryptage d'une édition qui s'annonce historique.",
    category: "Courses & Récits",
    categorySlug: "courses-recits",
    author: "Rédaction Altitude",
    date: "24 octobre 2024",
    readTime: "8 min",
    image: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=1200&q=80",
    featured: true,
    tags: ["Diagonale des Fous", "Réunion", "Ultra"],
  },
  {
    slug: "kilian-jornet-endurance",
    title: "Comment Kilian Jornet a redéfini les limites de l'endurance pure",
    excerpt: "Analyse de la carrière et des méthodes d'entraînement de la légende catalane du trail mondial.",
    category: "Actualités",
    categorySlug: "actualites",
    author: "Marc Dubois",
    date: "20 octobre 2024",
    readTime: "12 min",
    image: "https://images.unsplash.com/photo-1590659534532-ffc89be3e22b?w=800&q=80",
    tags: ["Kilian Jornet", "Performance"],
  },
  {
    slug: "chaussures-carbone-trail-2024",
    title: "Test Chaussures : Les meilleures plaques carbone pour le trail 2024",
    excerpt: "Notre sélection des meilleures chaussures à plaque carbone testées sur le terrain.",
    category: "Actualités",
    categorySlug: "actualites",
    author: "Sophie Martin",
    date: "18 octobre 2024",
    readTime: "5 min",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    tags: ["Équipement", "Chaussures"],
  },
  {
    slug: "nutrition-ultra-erreurs",
    title: "Nutrition : 5 erreurs fatales à éviter sur ultra-marathon",
    excerpt: "Les dernières études scientifiques montrent que la gestion de l'osmolalité est cruciale au-delà de 10h d'effort.",
    category: "Nutrition",
    categorySlug: "nutrition",
    author: "Dr. Paul Lefèvre",
    date: "15 octobre 2024",
    readTime: "7 min",
    image: "https://images.unsplash.com/photo-1554284126-aa88f22d8b74?w=800&q=80",
    tags: ["Nutrition", "Ultra", "Science"],
  },
  {
    slug: "utmb-2025-tirage",
    title: "UTMB 2025 : Les nouvelles règles de tirage au sort expliquées",
    excerpt: "World Athletics Running majors change les règles. Ce que ça change pour vous.",
    category: "Actualités",
    categorySlug: "actualites",
    author: "Rédaction Altitude",
    date: "12 octobre 2024",
    readTime: "4 min",
    image: "https://images.unsplash.com/photo-1502904550040-7534597429ae?w=800&q=80",
    tags: ["UTMB", "Réglementation"],
  },
  {
    slug: "trail-asie-du-sud-est",
    title: "Dossier : La montée en puissance du trail en Asie du Sud-Est",
    excerpt: "Vietnam, Thaïlande, Philippines — le trail explose dans toute la région. Reportage au cœur de cette révolution.",
    category: "Courses & Récits",
    categorySlug: "courses-recits",
    author: "Julie Nguyen",
    date: "10 octobre 2024",
    readTime: "15 min",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    tags: ["Asie", "Voyage"],
  },
  {
    slug: "hydratation-sel",
    title: "Hydratation : Pourquoi le sel est votre meilleur allié",
    excerpt: "Les électrolytes et leur rôle crucial dans la performance en trail longue distance.",
    category: "Nutrition",
    categorySlug: "nutrition",
    author: "Dr. Paul Lefèvre",
    date: "8 octobre 2024",
    readTime: "5 min",
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80",
    tags: ["Nutrition", "Hydratation"],
  },
  {
    slug: "calendrier-2025-top-10",
    title: "Calendrier : Les 10 courses à ne pas rater en 2025",
    excerpt: "De la Patagonie aux Alpes, notre sélection exclusive pour planifier votre saison.",
    category: "Courses & Récits",
    categorySlug: "courses-recits",
    author: "Marc Dubois",
    date: "5 octobre 2024",
    readTime: "6 min",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
    tags: ["Calendrier", "2025"],
  },
  {
    slug: "renforcement-excentrique",
    title: "Le renforcement excentrique pour les descentes",
    excerpt: "Pourquoi vos quadriceps vous lâchent en descente et comment y remédier avec 3 exercices clés.",
    category: "Entraînement & Performances",
    categorySlug: "entrainement",
    author: "Thomas Bernard",
    date: "2 octobre 2024",
    readTime: "8 min",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80",
    tags: ["Entraînement", "Force"],
  },
  {
    slug: "utmb-col-bonhomme",
    title: "UTMB : Les secrets de la montée vers le Col du Bonhomme",
    excerpt: "Stratégie, gestion de l'effort et mental — tout ce qu'il faut savoir sur ce passage emblématique.",
    category: "Courses & Récits",
    categorySlug: "courses-recits",
    author: "Marc Dubois",
    date: "28 septembre 2024",
    readTime: "10 min",
    image: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80",
    tags: ["UTMB", "Alpes", "Technique"],
  },
  {
    slug: "fkt-appalaches",
    title: "FKT : Nouveau record sur le Sentier des Appalaches",
    excerpt: "Un ultratraileur américain pulvérise le record de vitesse sur les 3 500 km du trail légendaire.",
    category: "Actualités",
    categorySlug: "actualites",
    author: "Rédaction Altitude",
    date: "25 septembre 2024",
    readTime: "5 min",
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80",
    tags: ["FKT", "Record"],
  },
  {
    slug: "debuter-trail-guide-complet",
    title: "Guide complet pour débuter le trail en 2024",
    excerpt: "Équipement, entraînement, nutrition — tout ce dont vous avez besoin pour vous lancer.",
    category: "Débuter",
    categorySlug: "debuter",
    author: "Sophie Martin",
    date: "20 septembre 2024",
    readTime: "20 min",
    image: "https://images.unsplash.com/photo-1476231682828-37e571bc172f?w=800&q=80",
    tags: ["Débutant", "Guide"],
  },
];

export const races: Race[] = [
  {
    id: "utmb",
    name: "Ultra-Trail du Mont-Blanc (UTMB)",
    location: "Chamonix",
    department: "Haute-Savoie (74)",
    region: "Auvergne-Rhône-Alpes",
    date: "25 août 2025",
    distance: "171 km",
    elevation: "+10 000 m",
    difficulty: "Extrême",
    website: "https://utmb.world",
    description: "La course de trail la plus emblématique au monde, autour du Mont-Blanc.",
  },
  {
    id: "grand-raid-reunion",
    name: "Diagonale des Fous",
    location: "Saint-Pierre, La Réunion",
    department: "La Réunion (974)",
    region: "Océan Indien",
    date: "17 octobre 2025",
    distance: "165 km",
    elevation: "+9 643 m",
    difficulty: "Extrême",
    website: "https://grandraid-reunion.com",
    description: "La traversée de l'île de la Réunion, une des courses les plus dures du monde.",
  },
  {
    id: "maxi-race-annecy",
    name: "Maxi-Race du Lac d'Annecy",
    location: "Annecy",
    department: "Haute-Savoie (74)",
    region: "Auvergne-Rhône-Alpes",
    date: "10 mai 2025",
    distance: "85 km",
    elevation: "+5 700 m",
    difficulty: "Difficile",
    website: "https://maxi-race.com",
    description: "Le tour du lac d'Annecy en trail, avec une vue imprenable sur les Alpes.",
  },
  {
    id: "ecotrail-paris",
    name: "EcoTrail de Paris",
    location: "Paris",
    department: "Ile-de-France (75)",
    region: "Île-de-France",
    date: "22 mars 2025",
    distance: "80 km",
    elevation: "+1 000 m",
    difficulty: "Modéré",
    website: "https://ecotrailparis.com",
    description: "Un trail autour de Paris, de Versailles au Trocadéro.",
  },
  {
    id: "transgrancanaria",
    name: "Trail des Templiers",
    location: "Millau",
    department: "Aveyron (12)",
    region: "Occitanie",
    date: "25 octobre 2025",
    distance: "73 km",
    elevation: "+3 800 m",
    difficulty: "Difficile",
    website: "https://traildesgrandscausses.com",
    description: "Un trail mythique dans les Gorges du Tarn et les Grands Causses.",
  },
  {
    id: "oxy-trail",
    name: "Oxy'Trail",
    location: "Forêt de Saint-Germain-en-Laye",
    department: "Yvelines (78)",
    region: "Île-de-France",
    date: "29 mars 2025",
    distance: "34 km",
    elevation: "+500 m",
    difficulty: "Facile",
    description: "Course idéale pour débuter, dans la forêt de Saint-Germain-en-Laye.",
  },
  {
    id: "trail-blanc-combloux",
    name: "Trail Blanc de Combloux",
    location: "Combloux",
    department: "Haute-Savoie (74)",
    region: "Auvergne-Rhône-Alpes",
    date: "15 janvier 2025",
    distance: "30 km",
    elevation: "+1 800 m",
    difficulty: "Difficile",
    description: "Un trail en conditions hivernales sur les pentes du Mont-Blanc.",
  },
  {
    id: "marathon-du-mont-blanc",
    name: "Marathon du Mont-Blanc",
    location: "Chamonix",
    department: "Haute-Savoie (74)",
    region: "Auvergne-Rhône-Alpes",
    date: "28 juin 2025",
    distance: "42 km",
    elevation: "+2 800 m",
    difficulty: "Difficile",
    website: "https://marathondumontblanc.fr",
    description: "42 km autour des aiguilles de Chamonix, un classique absolu.",
  },
  {
    id: "trail-du-golfe-du-morbihan",
    name: "Trail du Golfe du Morbihan",
    location: "Vannes",
    department: "Morbihan (56)",
    region: "Bretagne",
    date: "6 avril 2025",
    distance: "55 km",
    elevation: "+800 m",
    difficulty: "Modéré",
    description: "Un trail côtier magnifique autour du Golfe du Morbihan.",
  },
  {
    id: "trail-des-forts",
    name: "Trail des Forts",
    location: "Verdun",
    department: "Meuse (55)",
    region: "Grand Est",
    date: "18 mai 2025",
    distance: "50 km",
    elevation: "+1 200 m",
    difficulty: "Modéré",
    description: "Un trail dans les forêts chargées d'histoire autour de Verdun.",
  },
];

export const mostRead = articles.slice(0, 5);
export const featuredArticle = articles[0];
export const latestArticles = articles.slice(1, 7);
