import { Race } from "@/types";

// Base de données de courses trail françaises pour la saison 2026.
// Dataset restreint et vérifié : événements connus et récurrents dont la tenue en 2026
// est raisonnablement attendue. Les dates sont projetées à partir du créneau annuel
// habituel de chaque course et peuvent varier de quelques jours par rapport au programme
// officiel final. À enrichir via scripts/import-itra.mjs quand un export Betrail/ITRA
// sera disponible.

export const races: Race[] = [
  // ========== HAUTE-SAVOIE (74) — massif du Mont-Blanc ==========
  {
    id: "utmb-2026",
    slug: "utmb-mont-blanc-2026",
    name: "Ultra-Trail du Mont-Blanc (UTMB)",
    date: "28 août 2026",
    month: 8,
    dateISO: "2026-08-28",
    city: "Chamonix-Mont-Blanc",
    departmentCode: "74",
    departmentName: "Haute-Savoie",
    region: "Auvergne-Rhône-Alpes",
    distance: 171,
    elevation: 10000,
    difficulty: "Extrême",
    description:
      "La course d'ultra-trail la plus emblématique du monde, un tour complet du massif du Mont-Blanc entre France, Italie et Suisse.",
    lat: 45.9237,
    lng: 6.8694,
    website: "https://utmbmontblanc.com",
  },
  {
    id: "ccc-2026",
    slug: "ccc-courmayeur-champex-chamonix-2026",
    name: "CCC — Courmayeur, Champex, Chamonix",
    date: "28 août 2026",
    month: 8,
    dateISO: "2026-08-28",
    city: "Courmayeur → Chamonix",
    departmentCode: "74",
    departmentName: "Haute-Savoie",
    region: "Auvergne-Rhône-Alpes",
    distance: 101,
    elevation: 6100,
    difficulty: "Extrême",
    description:
      "La petite sœur de l'UTMB sur la deuxième moitié du tracé : départ en Italie, arrivée à Chamonix, 101 km à travers les plus beaux paysages du massif.",
    lat: 45.7886,
    lng: 6.9664,
    website: "https://utmbmontblanc.com",
  },
  {
    id: "tds-2026",
    slug: "tds-sur-les-traces-des-ducs-de-savoie-2026",
    name: "TDS — Sur les traces des Ducs de Savoie",
    date: "26 août 2026",
    month: 8,
    dateISO: "2026-08-26",
    city: "Courmayeur → Chamonix",
    departmentCode: "74",
    departmentName: "Haute-Savoie",
    region: "Auvergne-Rhône-Alpes",
    distance: 148,
    elevation: 9100,
    difficulty: "Extrême",
    description:
      "Itinéraire alternatif, plus sauvage et plus technique que l'UTMB, par les massifs du Beaufortain et des Contamines.",
    lat: 45.7886,
    lng: 6.9664,
    website: "https://utmbmontblanc.com",
  },
  {
    id: "occ-2026",
    slug: "occ-orsieres-champex-chamonix-2026",
    name: "OCC — Orsières, Champex, Chamonix",
    date: "27 août 2026",
    month: 8,
    dateISO: "2026-08-27",
    city: "Orsières → Chamonix",
    departmentCode: "74",
    departmentName: "Haute-Savoie",
    region: "Auvergne-Rhône-Alpes",
    distance: 56,
    elevation: 3500,
    difficulty: "Difficile",
    description:
      "Format plus court de l'UTMB Mont-Blanc : 56 km rapides depuis la Suisse jusqu'à la place du Triangle de l'Amitié.",
    lat: 46.0286,
    lng: 7.1486,
    website: "https://utmbmontblanc.com",
  },
  {
    id: "marathon-mont-blanc-2026",
    slug: "marathon-du-mont-blanc-2026",
    name: "Marathon du Mont-Blanc",
    date: "28 juin 2026",
    month: 6,
    dateISO: "2026-06-28",
    city: "Chamonix-Mont-Blanc",
    departmentCode: "74",
    departmentName: "Haute-Savoie",
    region: "Auvergne-Rhône-Alpes",
    distance: 42,
    elevation: 2500,
    difficulty: "Difficile",
    description:
      "Le classique de fin juin : 42 km alpins depuis Chamonix jusqu'au Brévent, avec l'arrivée face aux Grandes Jorasses.",
    lat: 45.9237,
    lng: 6.8694,
    website: "https://marathondumontblanc.com",
  },
  {
    id: "90km-mont-blanc-2026",
    slug: "90km-du-mont-blanc-2026",
    name: "90 km du Mont-Blanc",
    date: "27 juin 2026",
    month: 6,
    dateISO: "2026-06-27",
    city: "Chamonix-Mont-Blanc",
    departmentCode: "74",
    departmentName: "Haute-Savoie",
    region: "Auvergne-Rhône-Alpes",
    distance: 90,
    elevation: 6400,
    difficulty: "Extrême",
    description:
      "Reine de l'événement Mont-Blanc Marathon, 90 km en étoile autour de Chamonix avec les traversées emblématiques des Aiguilles Rouges.",
    lat: 45.9237,
    lng: 6.8694,
    website: "https://marathondumontblanc.com",
  },
  {
    id: "cross-mont-blanc-2026",
    slug: "cross-du-mont-blanc-2026",
    name: "Cross du Mont-Blanc",
    date: "29 juin 2026",
    month: 6,
    dateISO: "2026-06-29",
    city: "Chamonix-Mont-Blanc",
    departmentCode: "74",
    departmentName: "Haute-Savoie",
    region: "Auvergne-Rhône-Alpes",
    distance: 23,
    elevation: 1500,
    difficulty: "Difficile",
    description:
      "Format court du Mont-Blanc Marathon, 23 km explosifs depuis Chamonix jusqu'à Planpraz via les balcons de la vallée.",
    lat: 45.9237,
    lng: 6.8694,
    website: "https://marathondumontblanc.com",
  },
  {
    id: "km-vertical-chamonix-2026",
    slug: "km-vertical-de-chamonix-2026",
    name: "Vertical KM du Mont-Blanc",
    date: "27 juin 2026",
    month: 6,
    dateISO: "2026-06-27",
    city: "Chamonix-Mont-Blanc",
    departmentCode: "74",
    departmentName: "Haute-Savoie",
    region: "Auvergne-Rhône-Alpes",
    distance: 4,
    elevation: 1000,
    difficulty: "Difficile",
    description:
      "Le kilomètre vertical historique de Chamonix : 4 km, 1 000 m de dénivelé, un effort pur d'environ une demi-heure.",
    lat: 45.9237,
    lng: 6.8694,
    website: "https://marathondumontblanc.com",
  },
  {
    id: "maxi-race-annecy-2026",
    slug: "maxi-race-annecy-2026",
    name: "Maxi-Race d'Annecy",
    date: "30 mai 2026",
    month: 5,
    dateISO: "2026-05-30",
    city: "Annecy",
    departmentCode: "74",
    departmentName: "Haute-Savoie",
    region: "Auvergne-Rhône-Alpes",
    distance: 85,
    elevation: 5500,
    difficulty: "Difficile",
    description:
      "Un tour complet du lac d'Annecy en montagne, avec vue plongeante sur le lac depuis les crêtes du Semnoz et de la Tournette.",
    lat: 45.8992,
    lng: 6.1294,
    website: "https://maxi-race.com",
  },
  {
    id: "aiguilles-rouges-2026",
    slug: "trail-des-aiguilles-rouges-2026",
    name: "Trail des Aiguilles Rouges",
    date: "5 septembre 2026",
    month: 9,
    dateISO: "2026-09-05",
    city: "Vallorcine",
    departmentCode: "74",
    departmentName: "Haute-Savoie",
    region: "Auvergne-Rhône-Alpes",
    distance: 53,
    elevation: 3900,
    difficulty: "Difficile",
    description:
      "Traversée de la réserve naturelle des Aiguilles Rouges, face au massif du Mont-Blanc, sur des sentiers d'altitude techniques.",
    lat: 46.0333,
    lng: 6.9333,
  },

  // ========== SAVOIE (73) ==========
  {
    id: "6000d-la-plagne-2026",
    slug: "6000d-la-plagne-2026",
    name: "6000D — La course des géants",
    date: "25 juillet 2026",
    month: 7,
    dateISO: "2026-07-25",
    city: "La Plagne",
    departmentCode: "73",
    departmentName: "Savoie",
    region: "Auvergne-Rhône-Alpes",
    distance: 67,
    elevation: 3500,
    difficulty: "Difficile",
    description:
      "Le mythique 6000D relie Aime à La Plagne 2100 puis bascule vers le Sommet du Biolley, point culminant à 2 930 m.",
    lat: 45.5167,
    lng: 6.6833,
    website: "https://6000d.com",
  },
  {
    id: "courchevel-x3-2026",
    slug: "trail-de-courchevel-x3-2026",
    name: "Courchevel X3 — Trail des Trois Vallées",
    date: "18 juillet 2026",
    month: 7,
    dateISO: "2026-07-18",
    city: "Courchevel",
    departmentCode: "73",
    departmentName: "Savoie",
    region: "Auvergne-Rhône-Alpes",
    distance: 34,
    elevation: 2300,
    difficulty: "Difficile",
    description:
      "Un aller-retour à travers le domaine des Trois Vallées, avec les sommets de la Saulire et de la Vizelle comme points d'orgue.",
    lat: 45.4147,
    lng: 6.6352,
  },
  {
    id: "nivolet-revard-2026",
    slug: "trail-nivolet-revard-2026",
    name: "Trail Nivolet-Revard",
    date: "20 septembre 2026",
    month: 9,
    dateISO: "2026-09-20",
    city: "Le Bourget-du-Lac",
    departmentCode: "73",
    departmentName: "Savoie",
    region: "Auvergne-Rhône-Alpes",
    distance: 42,
    elevation: 2600,
    difficulty: "Difficile",
    description:
      "Un classique du massif des Bauges entre lac du Bourget et plateau du Revard, avec le passage de la Croix du Nivolet.",
    lat: 45.6439,
    lng: 5.8592,
  },

  // ========== HAUTES-ALPES (05) ==========
  {
    id: "galibier-meije-2026",
    slug: "trail-galibier-meije-gerard-tonnellier-2026",
    name: "Trail Galibier-Meije Gérard Tonnellier",
    date: "26 juillet 2026",
    month: 7,
    dateISO: "2026-07-26",
    city: "Valloire",
    departmentCode: "05",
    departmentName: "Hautes-Alpes",
    region: "Provence-Alpes-Côte d'Azur",
    distance: 75,
    elevation: 5200,
    difficulty: "Extrême",
    description:
      "Traversée exigeante des massifs du Galibier et de la Meije, entre Valloire et La Grave, au cœur d'un décor de haute montagne.",
    lat: 45.1647,
    lng: 6.4267,
  },
  {
    id: "trail-blanc-serre-chevalier-2026",
    slug: "trail-blanc-serre-chevalier-2026",
    name: "Trail Blanc de Serre Chevalier",
    date: "17 janvier 2026",
    month: 1,
    dateISO: "2026-01-17",
    city: "Briançon",
    departmentCode: "05",
    departmentName: "Hautes-Alpes",
    region: "Provence-Alpes-Côte d'Azur",
    distance: 21,
    elevation: 1100,
    difficulty: "Difficile",
    description:
      "Trail hivernal sur neige damée et sentiers gelés dans le domaine de Serre Chevalier, crampons conseillés.",
    lat: 44.9011,
    lng: 6.6442,
  },
  {
    id: "ubaye-trail-salomon-2026",
    slug: "ubaye-trail-salomon-2026",
    name: "Ubaye Trail Salomon",
    date: "4 juillet 2026",
    month: 7,
    dateISO: "2026-07-04",
    city: "Barcelonnette",
    departmentCode: "04",
    departmentName: "Alpes-de-Haute-Provence",
    region: "Provence-Alpes-Côte d'Azur",
    distance: 86,
    elevation: 6000,
    difficulty: "Extrême",
    description:
      "Le grand tour de l'Ubaye autour de Barcelonnette, entre hauts cols et vallées sauvages de la haute Provence.",
    lat: 44.3875,
    lng: 6.6517,
  },

  // ========== ISÈRE (38) ==========
  {
    id: "ut4m-grenoble-2026",
    slug: "ut4m-grenoble-2026",
    name: "Ultra Tour des 4 Massifs (UT4M)",
    date: "23 août 2026",
    month: 8,
    dateISO: "2026-08-23",
    city: "Grenoble",
    departmentCode: "38",
    departmentName: "Isère",
    region: "Auvergne-Rhône-Alpes",
    distance: 170,
    elevation: 11000,
    difficulty: "Extrême",
    description:
      "Le tour de la cuvette grenobloise à travers les quatre massifs : Chartreuse, Belledonne, Taillefer et Vercors.",
    lat: 45.1885,
    lng: 5.7245,
    website: "https://ut4m.fr",
  },
  {
    id: "passerelles-monteynard-2026",
    slug: "trail-des-passerelles-du-monteynard-2026",
    name: "Trail des Passerelles du Monteynard",
    date: "19 avril 2026",
    month: 4,
    dateISO: "2026-04-19",
    city: "Treffort",
    departmentCode: "38",
    departmentName: "Isère",
    region: "Auvergne-Rhône-Alpes",
    distance: 50,
    elevation: 2300,
    difficulty: "Difficile",
    description:
      "Les deux passerelles himalayennes du lac du Monteynard comme point de passage spectaculaire d'un trail au bord du Drac.",
    lat: 44.9275,
    lng: 5.6739,
  },
  {
    id: "trail-oisans-2026",
    slug: "trail-de-l-oisans-2026",
    name: "Trail de l'Oisans",
    date: "4 juillet 2026",
    month: 7,
    dateISO: "2026-07-04",
    city: "Bourg-d'Oisans",
    departmentCode: "38",
    departmentName: "Isère",
    region: "Auvergne-Rhône-Alpes",
    distance: 42,
    elevation: 2900,
    difficulty: "Difficile",
    description:
      "Un marathon de montagne dans le massif de l'Oisans, face aux géants des Grandes Rousses et de la Meije.",
    lat: 45.0519,
    lng: 6.0319,
  },

  // ========== ALPES-MARITIMES (06) ==========
  {
    id: "utcam-mercantour-2026",
    slug: "ultra-trail-cote-d-azur-mercantour-2026",
    name: "Ultra Trail Côte d'Azur Mercantour (UTCAM)",
    date: "26 septembre 2026",
    month: 9,
    dateISO: "2026-09-26",
    city: "Nice → Auron",
    departmentCode: "06",
    departmentName: "Alpes-Maritimes",
    region: "Provence-Alpes-Côte d'Azur",
    distance: 140,
    elevation: 9500,
    difficulty: "Extrême",
    description:
      "De la mer au ciel : départ sur la Promenade des Anglais, arrivée en haute montagne dans le parc du Mercantour.",
    lat: 43.7034,
    lng: 7.2663,
  },

  // ========== VAUCLUSE (84) ==========
  {
    id: "trail-ventoux-2026",
    slug: "trail-du-ventoux-2026",
    name: "Trail du Ventoux",
    date: "21 février 2026",
    month: 2,
    dateISO: "2026-02-21",
    city: "Bédoin",
    departmentCode: "84",
    departmentName: "Vaucluse",
    region: "Provence-Alpes-Côte d'Azur",
    distance: 46,
    elevation: 2200,
    difficulty: "Difficile",
    description:
      "Ascension du Géant de Provence par les sentiers forestiers et les pierriers emblématiques du sommet lunaire.",
    lat: 44.1233,
    lng: 5.1739,
  },

  // ========== BOUCHES-DU-RHÔNE (13) ==========
  {
    id: "trail-sainte-victoire-2026",
    slug: "trail-de-la-sainte-victoire-2026",
    name: "Trail de la Sainte-Victoire",
    date: "11 octobre 2026",
    month: 10,
    dateISO: "2026-10-11",
    city: "Puyloubier",
    departmentCode: "13",
    departmentName: "Bouches-du-Rhône",
    region: "Provence-Alpes-Côte d'Azur",
    distance: 48,
    elevation: 2100,
    difficulty: "Difficile",
    description:
      "Sur les traces de Cézanne, traversée de la barre calcaire emblématique de la Sainte-Victoire depuis Puyloubier.",
    lat: 43.5211,
    lng: 5.6625,
  },

  // ========== AVEYRON (12) — FESTIVAL DES TEMPLIERS ==========
  {
    id: "grande-course-templiers-2026",
    slug: "grande-course-des-templiers-2026",
    name: "Grande Course des Templiers",
    date: "25 octobre 2026",
    month: 10,
    dateISO: "2026-10-25",
    city: "Millau",
    departmentCode: "12",
    departmentName: "Aveyron",
    region: "Occitanie",
    distance: 76,
    elevation: 3300,
    difficulty: "Difficile",
    description:
      "La reine du Festival des Templiers, un tour complet des Grands Causses et des gorges du Tarn et de la Jonte.",
    lat: 44.0983,
    lng: 3.0786,
    website: "https://festival-des-templiers.com",
  },
  {
    id: "endurance-trail-templiers-2026",
    slug: "endurance-trail-des-templiers-2026",
    name: "Endurance Trail des Templiers",
    date: "24 octobre 2026",
    month: 10,
    dateISO: "2026-10-24",
    city: "Millau",
    departmentCode: "12",
    departmentName: "Aveyron",
    region: "Occitanie",
    distance: 105,
    elevation: 5000,
    difficulty: "Extrême",
    description:
      "L'ultra-distance du Festival des Templiers, 105 km à travers les causses et la vallée du Tarn.",
    lat: 44.0983,
    lng: 3.0786,
    website: "https://festival-des-templiers.com",
  },
  {
    id: "integrale-templiers-2026",
    slug: "l-integrale-des-templiers-2026",
    name: "L'Intégrale des Templiers",
    date: "24 octobre 2026",
    month: 10,
    dateISO: "2026-10-24",
    city: "Millau",
    departmentCode: "12",
    departmentName: "Aveyron",
    region: "Occitanie",
    distance: 32,
    elevation: 1300,
    difficulty: "Modéré",
    description:
      "Format accessible du Festival des Templiers : 32 km sur les plus beaux balcons du Causse Noir.",
    lat: 44.0983,
    lng: 3.0786,
    website: "https://festival-des-templiers.com",
  },

  // ========== CANTAL (15) ==========
  {
    id: "puy-mary-volcanic-2026",
    slug: "puy-mary-volcanic-trail-2026",
    name: "Puy Mary Volcanic Trail",
    date: "20 juin 2026",
    month: 6,
    dateISO: "2026-06-20",
    city: "Mandailles-Saint-Julien",
    departmentCode: "15",
    departmentName: "Cantal",
    region: "Auvergne-Rhône-Alpes",
    distance: 60,
    elevation: 3500,
    difficulty: "Difficile",
    description:
      "Traversée du plus grand volcan d'Europe, autour du Puy Mary et de ses vallées glaciaires rayonnantes.",
    lat: 45.1058,
    lng: 2.6833,
  },

  // ========== PUY-DE-DÔME (63) ==========
  {
    id: "trail-sancy-2026",
    slug: "trail-du-sancy-2026",
    name: "Trail du Sancy",
    date: "22 août 2026",
    month: 8,
    dateISO: "2026-08-22",
    city: "Le Mont-Dore",
    departmentCode: "63",
    departmentName: "Puy-de-Dôme",
    region: "Auvergne-Rhône-Alpes",
    distance: 50,
    elevation: 2700,
    difficulty: "Difficile",
    description:
      "Tour des monts Dore et ascension du Puy de Sancy, plus haut sommet du Massif Central (1 886 m).",
    lat: 45.5761,
    lng: 2.8086,
  },

  // ========== HAUTES-PYRÉNÉES (65) ==========
  {
    id: "grand-raid-pyrenees-2026",
    slug: "grand-raid-des-pyrenees-2026",
    name: "Grand Raid des Pyrénées (GRP)",
    date: "20 août 2026",
    month: 8,
    dateISO: "2026-08-20",
    city: "Vielle-Aure",
    departmentCode: "65",
    departmentName: "Hautes-Pyrénées",
    region: "Occitanie",
    distance: 160,
    elevation: 10000,
    difficulty: "Extrême",
    description:
      "Le plus grand ultra pyrénéen, entre vallée d'Aure et vallée de Luz, avec le passage des plus hauts cols du GR10.",
    lat: 42.8078,
    lng: 0.3533,
    website: "https://grandraidpyrenees.com",
  },
  {
    id: "tour-cirques-gavarnie-2026",
    slug: "tour-des-cirques-gavarnie-2026",
    name: "Tour des Cirques",
    date: "22 août 2026",
    month: 8,
    dateISO: "2026-08-22",
    city: "Gavarnie",
    departmentCode: "65",
    departmentName: "Hautes-Pyrénées",
    region: "Occitanie",
    distance: 100,
    elevation: 6500,
    difficulty: "Extrême",
    description:
      "Enchaînement des cirques de Gavarnie, Estaubé, Troumouse et du port de Boucharo, sur les plus hautes crêtes françaises.",
    lat: 42.7350,
    lng: -0.0097,
  },

  // ========== ARIÈGE (09) ==========
  {
    id: "trail-citadelles-2026",
    slug: "trail-des-citadelles-2026",
    name: "Trail des Citadelles",
    date: "9 mai 2026",
    month: 5,
    dateISO: "2026-05-09",
    city: "Mirepoix",
    departmentCode: "09",
    departmentName: "Ariège",
    region: "Occitanie",
    distance: 55,
    elevation: 2300,
    difficulty: "Difficile",
    description:
      "Un parcours historique à travers les châteaux cathares du piémont pyrénéen, autour de Mirepoix et Roquefixade.",
    lat: 43.0883,
    lng: 1.8744,
  },

  // ========== RHÔNE / LOIRE — SAINTÉLYON ==========
  {
    id: "saintelyon-2026",
    slug: "saintelyon-2026",
    name: "SaintéLyon",
    date: "5 décembre 2026",
    month: 12,
    dateISO: "2026-12-05",
    city: "Saint-Étienne → Lyon",
    departmentCode: "42",
    departmentName: "Loire",
    region: "Auvergne-Rhône-Alpes",
    distance: 78,
    elevation: 2000,
    difficulty: "Difficile",
    description:
      "La nocturne mythique entre Saint-Étienne et Lyon, 78 km à la frontale avec des milliers de lucioles dans la nuit.",
    lat: 45.4397,
    lng: 4.3872,
    website: "https://saintelyon.com",
  },

  // ========== JURA (39) ==========
  {
    id: "ultra-trail-jura-2026",
    slug: "ultra-trail-du-jura-2026",
    name: "Ultra Trail du Jura (UTJ)",
    date: "6 juin 2026",
    month: 6,
    dateISO: "2026-06-06",
    city: "Saint-Claude",
    departmentCode: "39",
    departmentName: "Jura",
    region: "Bourgogne-Franche-Comté",
    distance: 85,
    elevation: 4500,
    difficulty: "Difficile",
    description:
      "Traversée du haut Jura à travers combes et forêts, entre Saint-Claude et les crêtes de la haute chaîne.",
    lat: 46.3856,
    lng: 5.8636,
  },

  // ========== DOUBS (25) ==========
  {
    id: "trail-vauban-besancon-2026",
    slug: "trail-vauban-besancon-2026",
    name: "Trail Vauban de Besançon",
    date: "26 avril 2026",
    month: 4,
    dateISO: "2026-04-26",
    city: "Besançon",
    departmentCode: "25",
    departmentName: "Doubs",
    region: "Bourgogne-Franche-Comté",
    distance: 55,
    elevation: 1800,
    difficulty: "Difficile",
    description:
      "Un parcours autour des forts Vauban qui encerclent Besançon, avec la traversée de la Citadelle classée UNESCO.",
    lat: 47.2378,
    lng: 6.0241,
  },

  // ========== PARIS / ÎLE-DE-FRANCE ==========
  {
    id: "ecotrail-paris-2026",
    slug: "ecotrail-de-paris-2026",
    name: "EcoTrail de Paris",
    date: "21 mars 2026",
    month: 3,
    dateISO: "2026-03-21",
    city: "Paris / Versailles",
    departmentCode: "75",
    departmentName: "Paris",
    region: "Île-de-France",
    distance: 80,
    elevation: 1000,
    difficulty: "Modéré",
    description:
      "Un trail urbain et forestier depuis la forêt de Versailles jusqu'au pied de la Tour Eiffel, via les vallons du sud parisien.",
    lat: 48.8566,
    lng: 2.3522,
    website: "https://ecotrailparis.com",
  },
  {
    id: "oxy-trail-2026",
    slug: "oxy-trail-2026",
    name: "Oxy'Trail",
    date: "29 mars 2026",
    month: 3,
    dateISO: "2026-03-29",
    city: "Pontcarré",
    departmentCode: "77",
    departmentName: "Seine-et-Marne",
    region: "Île-de-France",
    distance: 34,
    elevation: 500,
    difficulty: "Facile",
    description:
      "Un trail nature idéal pour les débutants, à travers la forêt de Ferrières et les vallons de la Marne.",
    lat: 48.8000,
    lng: 2.7167,
  },
  {
    id: "trail-fontainebleau-2026",
    slug: "trail-de-fontainebleau-2026",
    name: "Trail de Fontainebleau",
    date: "10 mai 2026",
    month: 5,
    dateISO: "2026-05-10",
    city: "Fontainebleau",
    departmentCode: "77",
    departmentName: "Seine-et-Marne",
    region: "Île-de-France",
    distance: 50,
    elevation: 900,
    difficulty: "Modéré",
    description:
      "Trail mythique au cœur du plus grand massif forestier d'Île-de-France, sur les sentiers rocailleux de Bleau.",
    lat: 48.4047,
    lng: 2.7014,
  },

  // ========== MORBIHAN (56) ==========
  {
    id: "ultra-marin-morbihan-2026",
    slug: "ultra-marin-raid-du-golfe-du-morbihan-2026",
    name: "Ultra-Marin — Raid du Golfe du Morbihan",
    date: "20 juin 2026",
    month: 6,
    dateISO: "2026-06-20",
    city: "Vannes",
    departmentCode: "56",
    departmentName: "Morbihan",
    region: "Bretagne",
    distance: 177,
    elevation: 1200,
    difficulty: "Difficile",
    description:
      "Le plus long trail côtier de France, un tour complet du golfe du Morbihan par le GR 34.",
    lat: 47.6587,
    lng: -2.7600,
    website: "https://ultra-marin.fr",
  },

  // ========== ILLE-ET-VILAINE (35) ==========
  {
    id: "trail-broceliande-2026",
    slug: "trail-de-broceliande-2026",
    name: "Trail de Brocéliande",
    date: "17 mai 2026",
    month: 5,
    dateISO: "2026-05-17",
    city: "Paimpont",
    departmentCode: "35",
    departmentName: "Ille-et-Vilaine",
    region: "Bretagne",
    distance: 55,
    elevation: 1200,
    difficulty: "Modéré",
    description:
      "Un trail légendaire au cœur de la forêt de Brocéliande, entre le Val sans Retour et la fontaine de Barenton.",
    lat: 47.9878,
    lng: -2.1683,
  },

  // ========== CÔTES-D'ARMOR (22) ==========
  {
    id: "trail-cap-frehel-2026",
    slug: "trail-du-cap-frehel-2026",
    name: "Trail du Cap Fréhel",
    date: "3 mai 2026",
    month: 5,
    dateISO: "2026-05-03",
    city: "Plévenon",
    departmentCode: "22",
    departmentName: "Côtes-d'Armor",
    region: "Bretagne",
    distance: 40,
    elevation: 900,
    difficulty: "Modéré",
    description:
      "Trail côtier sur le GR 34 autour du cap Fréhel et du fort La Latte, au-dessus des plus hautes falaises bretonnes.",
    lat: 48.6833,
    lng: -2.3167,
  },

  // ========== MANCHE (50) ==========
  {
    id: "trail-mont-saint-michel-2026",
    slug: "trail-du-mont-saint-michel-2026",
    name: "Trail du Mont Saint-Michel",
    date: "13 juin 2026",
    month: 6,
    dateISO: "2026-06-13",
    city: "Genêts",
    departmentCode: "50",
    departmentName: "Manche",
    region: "Normandie",
    distance: 42,
    elevation: 600,
    difficulty: "Modéré",
    description:
      "Traversée de la baie et arrivée au pied du Mont Saint-Michel, avec une section pieds nus dans les sables mouvants.",
    lat: 48.6860,
    lng: -1.5110,
  },

  // ========== CORSE (2B) ==========
  {
    id: "restonica-trail-2026",
    slug: "restonica-trail-2026",
    name: "Restonica Trail",
    date: "27 juin 2026",
    month: 6,
    dateISO: "2026-06-27",
    city: "Corte",
    departmentCode: "2B",
    departmentName: "Haute-Corse",
    region: "Corse",
    distance: 110,
    elevation: 7500,
    difficulty: "Extrême",
    description:
      "Le plus dur trail corse : traversée des Aiguilles de Bavella et du massif du Monte Rotondo depuis Corte.",
    lat: 42.3069,
    lng: 9.1500,
  },

  // ========== RÉUNION (974) ==========
  {
    id: "diagonale-des-fous-2026",
    slug: "diagonale-des-fous-2026",
    name: "Diagonale des Fous (Grand Raid de La Réunion)",
    date: "15 octobre 2026",
    month: 10,
    dateISO: "2026-10-15",
    city: "Saint-Pierre → Saint-Denis",
    departmentCode: "974",
    departmentName: "La Réunion",
    region: "Océan Indien",
    distance: 165,
    elevation: 9600,
    difficulty: "Extrême",
    description:
      "La traversée intégrale de La Réunion du sud au nord, à travers les trois cirques et le volcan du Piton de la Fournaise.",
    lat: -21.3393,
    lng: 55.4781,
    website: "https://grandraid-reunion.com",
  },
  {
    id: "trail-bourbon-reunion-2026",
    slug: "trail-de-bourbon-reunion-2026",
    name: "Trail de Bourbon",
    date: "15 octobre 2026",
    month: 10,
    dateISO: "2026-10-15",
    city: "Cilaos → Saint-Denis",
    departmentCode: "974",
    departmentName: "La Réunion",
    region: "Océan Indien",
    distance: 111,
    elevation: 6500,
    difficulty: "Extrême",
    description:
      "Deuxième épreuve phare du Grand Raid de La Réunion, à travers les cirques de Cilaos, Mafate et Salazie.",
    lat: -21.1333,
    lng: 55.4667,
    website: "https://grandraid-reunion.com",
  },
  {
    id: "mascareignes-2026",
    slug: "mascareignes-reunion-2026",
    name: "La Mascareignes",
    date: "16 octobre 2026",
    month: 10,
    dateISO: "2026-10-16",
    city: "Grand Îlet → Saint-Denis",
    departmentCode: "974",
    departmentName: "La Réunion",
    region: "Océan Indien",
    distance: 70,
    elevation: 4000,
    difficulty: "Difficile",
    description:
      "Format intermédiaire du Grand Raid réunionnais, pour découvrir la traversée du cirque de Salazie jusqu'à l'arrivée à la Redoute.",
    lat: -21.0500,
    lng: 55.5667,
    website: "https://grandraid-reunion.com",
  },
  {
    id: "metis-trail-2026",
    slug: "metis-trail-reunion-2026",
    name: "Metis Trail",
    date: "17 octobre 2026",
    month: 10,
    dateISO: "2026-10-17",
    city: "La Possession → Saint-Denis",
    departmentCode: "974",
    departmentName: "La Réunion",
    region: "Océan Indien",
    distance: 27,
    elevation: 1600,
    difficulty: "Modéré",
    description:
      "Trail familial du Grand Raid, idéal pour découvrir les sentiers réunionnais sans partir à l'autre bout de l'île.",
    lat: -20.9250,
    lng: 55.3353,
    website: "https://grandraid-reunion.com",
  },

  // ========== HAUTE-LOIRE (43) ==========
  {
    id: "trail-meygal-2026",
    slug: "trail-du-meygal-2026",
    name: "Trail du Meygal",
    date: "13 septembre 2026",
    month: 9,
    dateISO: "2026-09-13",
    city: "Queyrières",
    departmentCode: "43",
    departmentName: "Haute-Loire",
    region: "Auvergne-Rhône-Alpes",
    distance: 45,
    elevation: 1800,
    difficulty: "Modéré",
    description:
      "Traversée du massif volcanique du Meygal, autour de Queyrières et des sucs basaltiques du Velay.",
    lat: 45.0825,
    lng: 4.1247,
  },

  // ========== VOSGES (88) ==========
  {
    id: "trail-hautes-vosges-2026",
    slug: "trail-des-hautes-vosges-2026",
    name: "Trail des Hautes-Vosges",
    date: "5 juillet 2026",
    month: 7,
    dateISO: "2026-07-05",
    city: "La Bresse",
    departmentCode: "88",
    departmentName: "Vosges",
    region: "Grand Est",
    distance: 56,
    elevation: 2400,
    difficulty: "Difficile",
    description:
      "Traversée des chaumes vosgiennes depuis La Bresse, par le Hohneck et les cirques glaciaires des lacs.",
    lat: 48.0003,
    lng: 6.8750,
  },

  // ========== GARD (30) ==========
  {
    id: "trail-cevennes-2026",
    slug: "trail-des-cevennes-2026",
    name: "Trail des Cévennes",
    date: "26 septembre 2026",
    month: 9,
    dateISO: "2026-09-26",
    city: "Saint-Jean-du-Gard",
    departmentCode: "30",
    departmentName: "Gard",
    region: "Occitanie",
    distance: 62,
    elevation: 3100,
    difficulty: "Difficile",
    description:
      "Sur les traces de Stevenson dans le Parc national des Cévennes, sentiers schisteux et vallées profondes.",
    lat: 44.1072,
    lng: 3.8758,
  },

  // ========== HÉRAULT (34) ==========
  {
    id: "trail-larzac-2026",
    slug: "trail-du-larzac-2026",
    name: "Trail du Larzac",
    date: "14 mars 2026",
    month: 3,
    dateISO: "2026-03-14",
    city: "La Couvertoirade",
    departmentCode: "34",
    departmentName: "Hérault",
    region: "Occitanie",
    distance: 38,
    elevation: 900,
    difficulty: "Modéré",
    description:
      "Parcours sur le causse du Larzac entre templiers et paysages lunaires, départ de la cité médiévale de La Couvertoirade.",
    lat: 43.9067,
    lng: 3.3147,
  },
];

export const RACE_DIFFICULTY_COLORS: Record<Race["difficulty"], string> = {
  "Facile": "#10b981",
  "Modéré": "#f59e0b",
  "Difficile": "#ea580c",
  "Extrême": "#dc2626",
};

export function distanceBucket(km: number): "<20" | "20-50" | "50-100" | ">100" {
  if (km < 20) return "<20";
  if (km < 50) return "20-50";
  if (km < 100) return "50-100";
  return ">100";
}

export const DISTANCE_BUCKETS: Array<{ value: "all" | "<20" | "20-50" | "50-100" | ">100"; label: string }> = [
  { value: "all", label: "Toutes distances" },
  { value: "<20", label: "Moins de 20 km" },
  { value: "20-50", label: "20 à 50 km" },
  { value: "50-100", label: "50 à 100 km" },
  { value: ">100", label: "Plus de 100 km" },
];

export const MONTHS_FR = [
  "janvier", "février", "mars", "avril", "mai", "juin",
  "juillet", "août", "septembre", "octobre", "novembre", "décembre",
];
